version: 2.1
description: "Allows CircleCI builds to access private network services over a intermediate jump host using SSH port forwarding."
commands:
  start_stats:
    parameters:
      stats_path:
        description: the relative or absolute directory for stats reports.
        default: circleci-stats
        type: string
    steps:
      - run:
          name: Install/Confirm utilitis (gawk, )
          command: |
            # debian and ubuntu *(perhaps others) basic awk does not have functions we need insralling gawk replaces awk
            sudo apt-get -y update && sudo apt-get -y install gawk || true  
      - run:
          name: Start background stats
          command: |
            mkdir -p <<parameters.stats_path>>
            while true;do sudo ps -Aorss,%cpu | sed '1d'  | awk '{mem += $1;cpu += $2}END{tmem = mem / 1024;tcpu = cpu / 1024; ts = strftime("%m/%d/%Y %H:%M:%S"); printf "%s %.2f MB, %.2f %\n", ts, tmem, tcpu}' >> <<parameters.stats_path>>/stats.txt;sleep 10; done
          background: true

  expose_stats:
    parameters:
      stats_path:
        description: the relative or absolute directory for stats reports.
        default: circleci-stats
        type: string
    steps:
      - run:
          name: Stats Summary
          command: |
            awk 'function bigger(val,max){if(val > max){return val}else{return max}}{hmem=bigger($3,hmem);hcpu=bigger($5,hcpu)}END{printf "Highest values:\nMemory:\t%.2f\nCPU:\t%.2f\n",hmem,hcpu}' <<parameters.stats_path>>/stats.txt
      - run:
          name: Print background stats
          command: |
            cat <<parameters.stats_path>>/*
      - store_artifacts:
          path: <<parameters.stats_path>>

jobs:
  with_stats:
    parameters:
      stats_path:
        description: the relative or absolute directory for stats reports.
        default: circleci-stats
        type: string
      executor:
        description: the executor to use for job
        default: default
        type: executor
      job_steps:
        description: Map of steps to run while collecting stats
        type: steps
    executor: <<parameters.executor>>
    steps:
      - checkout
      - start_stats:
          stats_path: <<parameters.stats_path>>
      - steps: <<parameters.job_steps>>
      - expose_stats:
          stats_path: <<parameters.stats_path>>


executors:
  default:
    parameters:
      docker_image:
        description: the docker image to use for job
        default: circleci/node:10
        type: string
    docker:
      - image: <<parameters.docker_image>>

examples:
  providing_key_as_path:
    description: Install stress and use memory
    usage:
      version: 2.1
      orbs:
        stats: eddiewebb/stats@volatile
      workflows:
        stress_stats:
          jobs:
            - stats/with_stats:
                job_steps:
                  - run: sudo apt-get update  && sudo apt-get -y install stress || true
                  - run: stress --vm 4 --timeout 30
